# Generated by Django 4.2.7 on 2025-08-07 23:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('name_fr', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=listings.models.pdf_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('auction_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('total_listings', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('listing_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('goods', 'Goods'), ('tools', 'Tools'), ('other', 'Other')], max_length=20)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('other', 'Other')], max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('guarantee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_url', models.URLField(blank=True)),
                ('original_pdf_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.auctiongroup')),
                ('pdf_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.pdfupload')),
            ],
            options={
                'ordering': ['lot_number'],
                'unique_together': {('lot_number', 'pdf_upload')},
            },
        ),
    ]
