# Generated by Django 4.2.7 on 2025-08-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for this listing', null=True),
        ),
    ]
